site_name: Black History Timeline
repo_url: https://github.com/Chukobyte/black-history-timeline
edit_uri: ""
site_description: A timeline of black history
site_author: Chukobyte
copyright: 'Copyright &copy; 2025 Chukobyte'

plugins:
  - search
  - mermaid2

theme:
  name: material

markdown_extensions:
  - pymdownx.highlight
  - pymdownx.superfences
  - pymdownx.inlinehilite

nav:
  - Introduction: index.md
  - Timeline: timeline.md
