site_name: Black History
repo_url: https://github.com/Chukobyte/black-history
edit_uri: ""
site_description: A work in progress black history project with a focus on black american history.  Made for black history month.
site_author: Chukobyte
copyright: 'Copyright &copy; 2025 Chukobyte'

plugins:
  - search
  - mermaid2

theme:
  name: windmill-dark

markdown_extensions:
  - pymdownx.highlight
  - pymdownx.superfences
  - pymdownx.inlinehilite

nav:
  - Home: index.md
  - Timeline:
    - Introduction: timeline/introduction.md
    - Pre-Translantic Slave Trade (Before 1619): timeline/pre_translantic_slave_trade.md
    - Translantic Slave Trade (1619–1865): timeline/translantic_slave_trade.md
    - Reconstruction (1865–1900): timeline/reconstruction.md
    - Cultural Renaissance and the Great Migration (1900–1940): timeline/cultural_renaissance_migration.md
    - The Civil Rights Movement (1940–1970): timeline/civil_rights.md
