site_name: Black History
repo_url: https://github.com/Chukobyte/black-history
edit_uri: ""
site_description: A work in progress black history project with a focus on black american history.  Made for black history month.
site_author: Chukobyte
copyright: 'Copyright &copy; 2025 Chukobyte'

plugins:
  - search
  - mermaid2

theme:
  name: material

markdown_extensions:
  - pymdownx.highlight
  - pymdownx.superfences
  - pymdownx.inlinehilite

nav:
  - Introduction: index.md
  - Timeline: timeline.md
