site_name: Black History
repo_url: https://github.com/Chukobyte/black-history
edit_uri: ""
site_description: A work in progress black history project with a focus on black american history.  Made for black history month.
site_author: Chukobyte
copyright: 'Copyright &copy; 2025 Chukobyte'

plugins:
  - search
  - mermaid2

theme:
  name: windmill-dark

markdown_extensions:
  - pymdownx.highlight
  - pymdownx.superfences
  - pymdownx.inlinehilite

nav:
  - Home: index.md
  - Timeline:
    - Pre-Translantic Slave Trade: timeline/pre_translantic_slave_trade.md
    - Translantic Slave Trade: timeline/translantic_slave_trade.md
    - Reconstruction: timeline/reconstruction.md
    - Cultural Renaissance and the Great Migration: timeline/cultural_renaissance_migration.md
    - The Civil Rights Movement: timeline/civil_rights.md
